// Auto-generated by dioxus-showcase. Do not edit by hand.
use dioxus::prelude::*;
use std::collections::HashSet;

pub type ComponentRenderFn = Box<dyn Fn() -> Element>;
pub const SHOWCASE_GENERATION: &str = "manifest-25d44d30a3bbbe0d";

pub struct ShowcaseComponentDefinition {
    pub id: String,
    pub title: String,
    pub tags: Vec<String>,
    pub render: ComponentRenderFn,
}

pub fn showcase_components() -> Vec<ShowcaseComponentDefinition> {
    let mut components = Vec::new();
    let mut ids = HashSet::new();
    for story in showcase_entry::button_variants::__dioxus_showcase_story__Button(r#"/workspace/src/button.rs"#, r#"button_variants::Button"#) {
        let story_id = story.definition.id.clone();
        assert!(ids.insert(story_id.clone()), "duplicate showcase id '{}'", story_id);
        components.push(ShowcaseComponentDefinition {
            id: story.definition.id,
            title: story.definition.title,
            tags: story.definition.tags,
            render: story.render,
        });
    }
    components
}
