use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use dioxus_showcase_core::ShowcaseConfig;

use crate::{
    build::rebuild_showcase_artifacts,
    cli::ExportArgs,
    commands::load_config,
    scaffold::{copy_dir_recursive, showcase_app_dir},
};

/// Marker file written into generated sites so re-exports can safely clear their own output.
const SITE_MARKER: &str = ".dioxus-showcase-site";

/// Directory `dx bundle` is pointed at before its output is flattened into the site directory.
const STAGING_DIR_NAME: &str = ".dx-bundle";

/// Builds the showcase app into a self-contained static website ready for any static host.
pub fn cmd_export(args: ExportArgs) -> Result<(), String> {
    let config = load_config()?;
    let component_count = rebuild_showcase_artifacts(&config)?;

    let requested_base_path = args.base_path.as_deref().unwrap_or(&config.build.base_path);
    let base_path = normalize_base_path(requested_base_path);
    let site_dir = absolute_path(resolve_site_dir(&config, args.out_dir.as_deref()))?;
    let app_dir = showcase_app_dir(&config);

    println!("Exporting {} showcase components to a static site.", component_count);
    prepare_site_dir(&site_dir)?;

    let staging_dir = site_dir.join(STAGING_DIR_NAME);
    run_dx_bundle(&app_dir, &staging_dir, base_path.as_deref(), args.debug)?;

    let bundle_root = locate_bundle_root(&staging_dir)?;
    copy_dir_recursive(&bundle_root, &site_dir)?;
    fs::remove_dir_all(&staging_dir)
        .map_err(|err| format!("failed to remove {}: {err}", staging_dir.display()))?;

    finalize_static_site(&site_dir)?;
    let pruned = prune_unreferenced_assets(&site_dir)?;
    if pruned > 0 {
        println!("Pruned {pruned} stale asset(s) left over from earlier builds.");
    }

    println!("Static site written to {}", site_dir.display());
    match base_path.as_deref() {
        Some(path) => println!("Serve it from the '/{path}' sub-path."),
        None => println!("Serve it from the domain root, or re-run with --base-path <PATH>."),
    }
    println!("Preview locally: python3 -m http.server --directory {}", site_dir.display());
    Ok(())
}

/// Resolves the site output directory from the CLI override or the configured build output.
fn resolve_site_dir(config: &ShowcaseConfig, out_dir_override: Option<&str>) -> PathBuf {
    match out_dir_override {
        Some(out_dir) => PathBuf::from(out_dir),
        None => PathBuf::from(&config.build.out_dir).join("site"),
    }
}

/// Makes a path absolute by resolving it against the current working directory when needed.
fn absolute_path(path: PathBuf) -> Result<PathBuf, String> {
    if path.is_absolute() {
        return Ok(path);
    }

    let cwd = env::current_dir().map_err(|err| format!("failed to read current dir: {err}"))?;
    Ok(cwd.join(path))
}

/// Trims a configured base path down to the slash-free form the Dioxus CLI expects.
fn normalize_base_path(base_path: &str) -> Option<String> {
    let trimmed = base_path.trim().trim_matches('/');
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_owned())
    }
}

/// Creates an empty site directory, refusing to clear directories the CLI did not generate.
fn prepare_site_dir(site_dir: &Path) -> Result<(), String> {
    if site_dir.exists() {
        if !site_dir.is_dir() {
            return Err(format!("{} exists but is not a directory", site_dir.display()));
        }

        let mut entries = fs::read_dir(site_dir)
            .map_err(|err| format!("failed to read {}: {err}", site_dir.display()))?;
        let is_empty = entries.next().is_none();

        if !is_empty && !site_dir.join(SITE_MARKER).exists() {
            return Err(format!(
                "{} is not empty and was not generated by dioxus-showcase. Remove it or pass --out-dir <DIR>.",
                site_dir.display()
            ));
        }

        fs::remove_dir_all(site_dir)
            .map_err(|err| format!("failed to clear {}: {err}", site_dir.display()))?;
    }

    fs::create_dir_all(site_dir)
        .map_err(|err| format!("failed to create {}: {err}", site_dir.display()))?;
    write_site_marker(site_dir)
}

/// Writes the marker that identifies a directory as generated showcase site output.
fn write_site_marker(site_dir: &Path) -> Result<(), String> {
    let marker_path = site_dir.join(SITE_MARKER);
    fs::write(&marker_path, "generated by dioxus-showcase export\n")
        .map_err(|err| format!("failed to create {}: {err}", marker_path.display()))
}

/// Invokes `dx bundle` for the web platform against the generated showcase app crate.
fn run_dx_bundle(
    app_dir: &Path,
    staging_dir: &Path,
    base_path: Option<&str>,
    debug: bool,
) -> Result<(), String> {
    if !app_dir.exists() {
        return Err(format!(
            "showcase app crate not found at {}. Run `dioxus-showcase init` first.",
            app_dir.display()
        ));
    }

    let mut command = Command::new("dx");
    command.arg("bundle").arg("--platform").arg("web");
    command.arg("--out-dir").arg(staging_dir);
    if !debug {
        // Release sites should not ship DWARF sections; they also break `wasm-opt`.
        command.arg("--release").arg("--debug-symbols=false");
    }
    if let Some(base_path) = base_path {
        command.arg("--base-path").arg(base_path);
    }

    let status = command.current_dir(app_dir).status().map_err(|err| {
        format!(
            "failed to run `dx bundle`. Ensure Dioxus CLI is installed and available in PATH: {err}"
        )
    })?;

    if status.success() {
        Ok(())
    } else {
        Err(format!("`dx bundle` exited with status {status}"))
    }
}

/// Finds the directory holding `index.html` inside the bundle output.
fn locate_bundle_root(staging_dir: &Path) -> Result<PathBuf, String> {
    let public_dir = staging_dir.join("public");
    if public_dir.join("index.html").exists() {
        return Ok(public_dir);
    }
    if staging_dir.join("index.html").exists() {
        return Ok(staging_dir.to_path_buf());
    }

    Err(format!("`dx bundle` produced no index.html under {}", staging_dir.display()))
}

/// Adds the fallback and host hint files a client-routed static site needs.
fn finalize_static_site(site_dir: &Path) -> Result<(), String> {
    let index_path = site_dir.join("index.html");
    let index_html = fs::read_to_string(&index_path)
        .map_err(|err| format!("failed to read {}: {err}", index_path.display()))?;

    // Static hosts serve 404.html for unknown paths, which is how deep story routes
    // such as /component/atoms-button survive a hard refresh.
    let not_found_path = site_dir.join("404.html");
    fs::write(&not_found_path, &index_html)
        .map_err(|err| format!("failed to create {}: {err}", not_found_path.display()))?;

    // GitHub Pages runs Jekyll by default, which drops files it considers private.
    let nojekyll_path = site_dir.join(".nojekyll");
    fs::write(&nojekyll_path, "")
        .map_err(|err| format!("failed to create {}: {err}", nojekyll_path.display()))?;

    write_site_marker(site_dir)
}

/// Deletes bundled assets that nothing in the exported site references.
///
/// The Dioxus CLI keeps every content-hashed asset it has ever produced in its own
/// staging directory and copies the whole directory into the bundle, so without this
/// a site re-exported ten times ships ten wasm binaries.
fn prune_unreferenced_assets(site_dir: &Path) -> Result<usize, String> {
    let assets_dir = site_dir.join("assets");
    if !assets_dir.is_dir() {
        return Ok(0);
    }

    let mut candidates = Vec::new();
    collect_files(&assets_dir, &mut candidates)?;

    // Everything outside `assets/` (index.html, 404.html) is an entry point.
    let mut roots = Vec::new();
    collect_files_shallow(site_dir, &mut roots)?;

    let mut reachable = vec![false; candidates.len()];
    let mut pending = roots;

    // Asset names are literals inside the files that use them: html references js,
    // js references the wasm binary, and the wasm embeds the names of its own assets.
    while let Some(file) = pending.pop() {
        let contents =
            fs::read(&file).map_err(|err| format!("failed to read {}: {err}", file.display()))?;

        for (index, candidate) in candidates.iter().enumerate() {
            if reachable[index] {
                continue;
            }
            let Some(name) = candidate.file_name().and_then(|name| name.to_str()) else {
                continue;
            };
            if contains_bytes(&contents, name.as_bytes()) {
                reachable[index] = true;
                pending.push(candidate.clone());
            }
        }
    }

    let mut pruned = 0;
    for (index, candidate) in candidates.iter().enumerate() {
        if reachable[index] {
            continue;
        }
        fs::remove_file(candidate)
            .map_err(|err| format!("failed to remove {}: {err}", candidate.display()))?;
        pruned += 1;
    }

    Ok(pruned)
}

/// Returns `true` when `haystack` contains `needle` as a contiguous byte sequence.
fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || needle.len() > haystack.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|window| window == needle)
}

/// Collects every file in a directory tree.
fn collect_files(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in
        fs::read_dir(dir).map_err(|err| format!("failed to read {}: {err}", dir.display()))?
    {
        let entry =
            entry.map_err(|err| format!("failed to read {} entry: {err}", dir.display()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else {
            files.push(path);
        }
    }
    Ok(())
}

/// Collects the files directly inside a directory, ignoring subdirectories.
fn collect_files_shallow(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in
        fs::read_dir(dir).map_err(|err| format!("failed to read {}: {err}", dir.display()))?
    {
        let entry =
            entry.map_err(|err| format!("failed to read {} entry: {err}", dir.display()))?;
        let path = entry.path();
        if path.is_file() {
            files.push(path);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    use dioxus_showcase_core::ShowcaseConfig;

    use super::{
        finalize_static_site, locate_bundle_root, normalize_base_path, prepare_site_dir,
        prune_unreferenced_assets, resolve_site_dir, SITE_MARKER,
    };

    fn temp_dir(prefix: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock should be monotonic")
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("{prefix}-{unique}"));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        dir
    }

    #[test]
    fn site_dir_defaults_to_site_under_build_out_dir() {
        let mut config = ShowcaseConfig::default();
        config.build.out_dir = "target/showcase".to_owned();

        assert_eq!(resolve_site_dir(&config, None), PathBuf::from("target/showcase/site"));
        assert_eq!(resolve_site_dir(&config, Some("docs/ui")), PathBuf::from("docs/ui"));
    }

    #[test]
    fn base_path_normalizes_to_slash_free_segments() {
        assert_eq!(normalize_base_path("/"), None);
        assert_eq!(normalize_base_path(""), None);
        assert_eq!(normalize_base_path("   "), None);
        assert_eq!(normalize_base_path("/my-repo"), Some("my-repo".to_owned()));
        assert_eq!(normalize_base_path("my-repo/"), Some("my-repo".to_owned()));
        assert_eq!(normalize_base_path("/nested/path/"), Some("nested/path".to_owned()));
    }

    #[test]
    fn prepare_site_dir_creates_and_marks_a_fresh_directory() {
        let dir = temp_dir("dioxus-showcase-export-fresh");
        let site_dir = dir.join("site");

        prepare_site_dir(&site_dir).expect("prepare fresh site dir");

        assert!(site_dir.join(SITE_MARKER).exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn prepare_site_dir_clears_previously_generated_output() {
        let dir = temp_dir("dioxus-showcase-export-reexport");
        let site_dir = dir.join("site");

        prepare_site_dir(&site_dir).expect("first export");
        std::fs::write(site_dir.join("stale.js"), "stale").expect("write stale asset");

        prepare_site_dir(&site_dir).expect("second export");

        assert!(!site_dir.join("stale.js").exists());
        assert!(site_dir.join(SITE_MARKER).exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn prepare_site_dir_refuses_to_clear_foreign_directories() {
        let dir = temp_dir("dioxus-showcase-export-foreign");
        let site_dir = dir.join("docs");
        std::fs::create_dir_all(&site_dir).expect("create docs dir");
        std::fs::write(site_dir.join("handwritten.md"), "keep me").expect("write doc");

        let err = prepare_site_dir(&site_dir).expect_err("foreign directory must be refused");

        assert!(err.contains("was not generated by dioxus-showcase"));
        assert!(site_dir.join("handwritten.md").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn locate_bundle_root_prefers_the_public_subdirectory() {
        let dir = temp_dir("dioxus-showcase-export-bundle-root");
        let staging = dir.join("staging");
        let public = staging.join("public");
        std::fs::create_dir_all(&public).expect("create public dir");
        std::fs::write(public.join("index.html"), "<html></html>").expect("write index");

        assert_eq!(locate_bundle_root(&staging).expect("locate root"), public);

        let flat = dir.join("flat");
        std::fs::create_dir_all(&flat).expect("create flat dir");
        std::fs::write(flat.join("index.html"), "<html></html>").expect("write index");
        assert_eq!(locate_bundle_root(&flat).expect("locate flat root"), flat);

        let empty = dir.join("empty");
        std::fs::create_dir_all(&empty).expect("create empty dir");
        assert!(locate_bundle_root(&empty).expect_err("empty bundle").contains("no index.html"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn prune_keeps_transitively_referenced_assets_and_drops_the_rest() {
        let dir = temp_dir("dioxus-showcase-export-prune");
        let site_dir = dir.join("site");
        let assets_dir = site_dir.join("assets");
        std::fs::create_dir_all(&assets_dir).expect("create assets dir");

        std::fs::write(
            site_dir.join("index.html"),
            "<script src=\"/assets/app-dxh111.js\"></script>",
        )
        .expect("write index");
        // The js glue names the wasm, which in turn embeds the css asset name.
        std::fs::write(assets_dir.join("app-dxh111.js"), "fetch('app_bg-dxh222.wasm')")
            .expect("write js");
        std::fs::write(assets_dir.join("app_bg-dxh222.wasm"), b"\0\0style-dxh333.css\0\0")
            .expect("write wasm");
        std::fs::write(assets_dir.join("style-dxh333.css"), "body{}").expect("write css");
        // Left behind by an earlier build with different content hashes.
        std::fs::write(assets_dir.join("app-dxh999.js"), "stale").expect("write stale js");
        std::fs::write(assets_dir.join("app_bg-dxh888.wasm"), "stale").expect("write stale wasm");

        let pruned = prune_unreferenced_assets(&site_dir).expect("prune assets");

        assert_eq!(pruned, 2);
        assert!(assets_dir.join("app-dxh111.js").exists());
        assert!(assets_dir.join("app_bg-dxh222.wasm").exists());
        assert!(assets_dir.join("style-dxh333.css").exists());
        assert!(!assets_dir.join("app-dxh999.js").exists());
        assert!(!assets_dir.join("app_bg-dxh888.wasm").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn prune_is_a_no_op_without_an_assets_directory() {
        let dir = temp_dir("dioxus-showcase-export-prune-empty");
        let site_dir = dir.join("site");
        std::fs::create_dir_all(&site_dir).expect("create site dir");
        std::fs::write(site_dir.join("index.html"), "<html></html>").expect("write index");

        assert_eq!(prune_unreferenced_assets(&site_dir).expect("prune"), 0);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn finalize_static_site_adds_spa_fallback_and_host_hints() {
        let dir = temp_dir("dioxus-showcase-export-finalize");
        let site_dir = dir.join("site");
        std::fs::create_dir_all(&site_dir).expect("create site dir");
        std::fs::write(site_dir.join("index.html"), "<html>app</html>").expect("write index");

        finalize_static_site(&site_dir).expect("finalize site");

        assert_eq!(
            std::fs::read_to_string(site_dir.join("404.html")).expect("read fallback"),
            "<html>app</html>"
        );
        assert!(site_dir.join(".nojekyll").exists());
        assert!(site_dir.join(SITE_MARKER).exists());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
